sudo: required
dist: trusty
language: node_js
node_js:
  - "node"
addons:
  # From some tests it seems you can only have one firefox addon.
  # Adding two results in the last one defined being the one installed.
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - sudo apt-get update -qq
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm install -g web-component-tester@4.2.2
  - npm install -g bower
  - npm install -g eslint-config-airbnb@12.0.0 eslint@3.6.1 eslint-plugin-jsx-a11y@2.2.2 eslint-plugin-import@1.16.0 eslint-plugin-react@6.3.0
  - bower install
script:
  - eslint src/
  - wct --skip-plugin sauce --plugin local -l chrome
